SHELL=/bin/sh

CFLAGS = -Wall -pedantic -g

EXECUTABLES=	cree_core		\
		exemple_buffers		\
		exemple_enum		\
		exemple_fopen		\
		exemple_freopen		\
		exemple_fseeko		\
		exemple_fseeko_2	\
		exemple_ftell		\
		exemple_fwrite		\


all : ${EXECUTABLES}

clean : 
	@rm -f core* *.o *.out essai.*
	@rm -f ${EXECUTABLES}
