SHELL=/bin/sh

CFLAGS = -Wall -g

EXECUTABLES=					\
		exemple_gethostby		\
		exemple_gethostent		\
		exemple_getprotoby		\
		exemple_getprotoent		\
		exemple_getservby		\
		exemple_getservent_r		\
		exemple_inet_aton		\
		exemple_inet_netof		\
		exemple_inet_pton		\
		masque_reseau			\
		ordre_octets			\


all : ${EXECUTABLES}

clean : 
	@rm -f core* *.o *.out essai.*
	@rm -f ${EXECUTABLES}
