SHELL=/bin/sh

CFLAGS = -Wall -g -pedantic

EXECUTABLES=	exemple_pipe_1		\
		exemple_pipe_2		\
		exemple_pipe_3		\
		exemple_pipe_4		\
		exemple_pipe_5		\
		exemple_pipe_6		\
		exemple_pipe_7		\
		exemple_pipe_8		\
		exemple_client		\
		exemple_serveur		\


all : ${EXECUTABLES}

clean : 
	@rm -f core* *.o *.out essai.*
	@rm -f ${EXECUTABLES}
