SHELL=/bin/sh

CFLAGS = -Wall -g

EXECUTABLES=				\
		exemple_atoi		\
		exemple_ecvt		\
		exemple_is		\
		exemple_sizeof		\
		exemple_strtof		\
		exemple_strtol		\


all : ${EXECUTABLES}

clean : 
	@rm -f core* *.o *.out essai.*
	@rm -f ${EXECUTABLES}
