SHELL=/bin/sh

CFLAGS = -Wall -pedantic -g

EXECUTABLES=	exemple_memcmp			\
		exemple_stpncpy			\
		exemple_strcasecmp		\
		exemple_strcasestr		\
		exemple_strcoll			\
		exemple_strcmp 			\
		exemple_strncat			\
		exemple_strsep			\
		exemple_strstr			\
		exemple_strtok			\
		exemple_strtok_r		\
		exemple_strxfrm			\
		exemple_strxfrm_2		\


all : ${EXECUTABLES}


clean : 
	@rm -f core *.o *.out
	@rm -f ${EXECUTABLES}
