SHELL=/bin/sh

CFLAGS = -Wall -g -pedantic -lm

EXECUTABLES=	exemple_math_1		\
		exemple_math_2		\
		exemple_math_3		\


all : ${EXECUTABLES}

clean : 
	@rm -f core* *.o *.out essai.*
	@rm -f ${EXECUTABLES}
