SHELL=/bin/sh

CFLAGS = -Wall -pedantic -g

EXECUTABLES=	exemple_fgetc			\
		exemple_fgets			\
		exemple_fprintf_1		\
		exemple_fprintf_2		\
		exemple_fprintf_3		\
		exemple_fprintf_4		\
		exemple_fprintf_5		\
		exemple_fputc			\
		exemple_fputs			\
		exemple_getchar			\
		exemple_getline			\
		exemple_gets			\
		exemple_pile			\
		exemple_puts			\
		exemple_scanf_1			\
		exemple_scanf_2			\
		exemple_scanf_3			\
		exemple_scanf_4			\
		exemple_scanf_5			\
		exemple_scanf_6			\
		exemple_scanf_7			\
		exemple_scanf_8			\
		exemple_ungetc			\
		exemple_vsnprintf		\


all : ${EXECUTABLES}

clean : 
	@rm -f core *.o *.out
	@rm -f ${EXECUTABLES}
