SHELL=/bin/sh

CFLAGS = -Wall -pedantic -g

EXECUTABLES=	exemple_hsearch		\
		exemple_hsearch_r	\
		exemple_qsort		\
		exemple_qsort_2		\
		exemple_tsearch		\


all : ${EXECUTABLES}

clean : 
	@rm -f core *.o *.out
	@rm -f ${EXECUTABLES}
